baseURL = 'https://guitarcompendium.com/'
languageCode = 'en-us'
title = 'Guitar Compendium'
theme = "hugo-theme-monochrome"

[params]
navbar_title = "Guitar Compendium" # default: site's `title`
footer = "Copyright © {{year}} by Lucas Gôuvea" # default: None
enable_collapsible_toc = true # default: false