#!/usr/bin/bash
 convert a_arte_da_improvisação_parte_1.png -resize 10% a_arte_da_improvisação_parte_1.png
 convert balloon.png -resize 10% balloon.png
 convert balloon_dark.png -resize 10% balloon_dark.png
 convert berklee/a_modern_method_for_guitar_berklee_1.png -resize 10% berklee/a_modern_method_for_guitar_berklee_1.png
 convert berklee/a_modern_method_for_guitar_berklee_2.png -resize 10% berklee/a_modern_method_for_guitar_berklee_2.png
 convert berklee/a_modern_method_for_guitar_berklee_3.png -resize 10% berklee/a_modern_method_for_guitar_berklee_3.png
 convert bookcase.png -resize 10% bookcase.png
 convert bookcase_dark.png -resize 10% bookcase_dark.png
 convert catalogue.png -resize 10% catalogue.png
 convert catalogue_dark.png -resize 10% catalogue_dark.png
 convert chordbible.png -resize 10% chordbible.png
 convert coding.png -resize 10% coding.png
 convert coding_dark.png -resize 10% coding_dark.png
 convert desktop.png -resize 10% desktop.png
 convert desktop_dark.png -resize 10% desktop_dark.png
 convert escala_diminuta__dom_dim.png -resize 10% escala_diminuta__dom_dim.png
 convert guia_ilustrado_da_guitarra.png -resize 10% guia_ilustrado_da_guitarra.png
 convert guia_ilustrado_da_guitarra_manual_de_conhecimentos_e_reparos_essenciais_edmar_luighi.png -resize 10% guia_ilustrado_da_guitarra_manual_de_conhecimentos_e_reparos_essenciais_edmar_luighi.png
 convert kenny_werner_effortless_mastery_liberating_the_master_musician_within.png -resize 10% kenny_werner_effortless_mastery_liberating_the_master_musician_within.png
 convert list.png -resize 10% list.png
 convert list_dark.png -resize 10% list_dark.png
 convert martin_koch.png -resize 10% martin_koch.png
 convert método_de_guitarra.png -resize 10% método_de_guitarra.png
 convert picture.png -resize 10% picture.png
 convert picture_dark.png -resize 10% picture_dark.png
 convert scalearpeggio.png -resize 10% scalearpeggio.png
 convert sheila_davis_the_craft_of_lyric_writing.png -resize 10% sheila_davis_the_craft_of_lyric_writing.png
 convert steve_vai__30hr_guitar_workout_complete.png -resize 10% steve_vai__30hr_guitar_workout_complete.png
 convert teoria/0102pitchnotation.png -resize 10% teoria/0102pitchnotation.png
 convert teoria/0103rhythmnotation.png -resize 10% teoria/0103rhythmnotation.png
 convert teoria/0104meter.png -resize 10% teoria/0104meter.png
 convert teoria/0105majorscales.png -resize 10% teoria/0105majorscales.png
 convert teoria/0106keysignatures.png -resize 10% teoria/0106keysignatures.png
 convert teoria/0107circleoffifths.png -resize 10% teoria/0107circleoffifths.png
 convert teoria/0109perfectintervals.png -resize 10% teoria/0109perfectintervals.png
 convert teoria/0110imperfectintervals.png -resize 10% teoria/0110imperfectintervals.png
 convert teoria/0111minorscales.png -resize 10% teoria/0111minorscales.png
 convert teoria/0112triads.png -resize 10% teoria/0112triads.png
 convert teoria/0113triadsininversion.png -resize 10% teoria/0113triadsininversion.png
 convert teoria/0114figuredbass.png -resize 10% teoria/0114figuredbass.png
 convert teoria/0115triadswithintonality.png -resize 10% teoria/0115triadswithintonality.png
 convert teoria/0201introtopartwriting.png -resize 10% teoria/0201introtopartwriting.png
 convert teoria/0202partwritingvertical.png -resize 10% teoria/0202partwritingvertical.png
 convert teoria/0203partwritinghorizontal.png -resize 10% teoria/0203partwritinghorizontal.png
 convert teoria/0204partwritinginversions.png -resize 10% teoria/0204partwritinginversions.png
 convert teoria/0205partwritingmelodicminor.png -resize 10% teoria/0205partwritingmelodicminor.png
 convert teoria/0206harmoniccadences.png -resize 10% teoria/0206harmoniccadences.png
 convert teoria/0207harmonicprogression.png -resize 10% teoria/0207harmonicprogression.png
 convert teoria/0208diatoniccommonchordmodulation.png -resize 10% teoria/0208diatoniccommonchordmodulation.png
 convert teoria/0209nonharmonictones.png -resize 10% teoria/0209nonharmonictones.png
 convert teoria/0210motivicdevelopment.png -resize 10% teoria/0210motivicdevelopment.png
 convert teoria/0211binaryform.png -resize 10% teoria/0211binaryform.png
 convert teoria/0212ternaryform.png -resize 10% teoria/0212ternaryform.png
 convert teoria/0213sonataallegroform.png -resize 10% teoria/0213sonataallegroform.png
 convert teoria/0301diatonicseventhchords.png -resize 10% teoria/0301diatonicseventhchords.png
 convert teoria/0302thedominantseventh.png -resize 10% teoria/0302thedominantseventh.png
 convert teoria/0303extendedharmonies.png -resize 10% teoria/0303extendedharmonies.png
 convert teoria/0304alteredchords.png -resize 10% teoria/0304alteredchords.png
 convert teoria/0305borrowedchords.png -resize 10% teoria/0305borrowedchords.png
 convert teoria/0306neapolitansix.png -resize 10% teoria/0306neapolitansix.png
 convert teoria/0307secondarydominants.png -resize 10% teoria/0307secondarydominants.png
 convert teoria/0308augmentedsixths.png -resize 10% teoria/0308augmentedsixths.png
 convert teoria/0310secondarysubdominants.png -resize 10% teoria/0310secondarysubdominants.png
 convert teoria/0311romanticeratechniques.png -resize 10% teoria/0311romanticeratechniques.png
 convert teoria/0401modes.png -resize 10% teoria/0401modes.png
 convert teoria/SC01introtospecies.png -resize 10% teoria/SC01introtospecies.png
 convert teoria/SC02melody.png -resize 10% teoria/SC02melody.png
 convert teoria/SC03speciesone.png -resize 10% teoria/SC03speciesone.png
 convert teoria/SC04speciestwo.png -resize 10% teoria/SC04speciestwo.png
 convert teoria/SC05speciesthree.png -resize 10% teoria/SC05speciesthree.png
 convert teoria/SC06speciesfour.png -resize 10% teoria/SC06speciesfour.png
 convert teoria/SC07speciesfive.png -resize 10% teoria/SC07speciesfive.png
 convert teoria/SP01beaming.png -resize 10% teoria/SP01beaming.png
 convert teoria/SP02intervals.png -resize 10% teoria/SP02intervals.png
 convert teoria/SP03suspensions.png -resize 10% teoria/SP03suspensions.png
 convert total_guitar__the_ultimate_scale_book.png -resize 10% total_guitar__the_ultimate_scale_book.png
 convert vase.png -resize 10% vase.png
 convert vase_dark.png -resize 10% vase_dark.png
 convert wooten.png -resize 10% wooten.png
 convert writing_better_lyrics_2nd_edition.png -resize 10% writing_better_lyrics_2nd_edition.png
 convert zen_guitar_philip_toshio_sudo.png -resize 10% zen_guitar_philip_toshio_sudo.png
